In [12]:

import torch
a = torch.ones(3)
print(a)

tensor([1., 1., 1.])


In [15]:
img_t = torch.randn(3, 6, 4)
print(img_t)

tensor([[[ 4.9711e-01,  5.2724e-01,  4.8972e-01, -1.3887e+00],
         [-7.2809e-01, -8.2606e-01,  4.9367e-01, -9.0505e-04],
         [ 2.6912e-01, -1.0768e+00,  3.1310e-01, -1.9020e-01],
         [-9.5672e-01,  7.4705e-01, -2.0208e-01,  7.6062e-01],
         [ 4.8592e-01, -2.9162e+00,  1.8533e+00, -1.4108e+00],
         [ 5.9586e-02, -2.2146e+00,  6.4198e-01,  9.0645e-01]],

        [[ 1.5673e+00, -9.1918e-01, -1.4988e-01,  2.2854e-02],
         [ 4.1503e-01, -1.3055e+00,  1.0290e+00,  1.4328e+00],
         [ 9.1018e-01, -7.4784e-01,  6.6186e-02,  2.0214e+00],
         [-1.3259e+00,  1.0301e+00,  8.6322e-01,  1.2495e-01],
         [-2.3971e-02, -8.8491e-01, -9.2280e-02,  1.0762e+00],
         [-9.0535e-01, -4.6792e-01,  1.2787e-01,  1.6849e+00]],

        [[-8.1678e-01,  4.7375e-01,  1.1198e+00,  1.4274e+00],
         [-1.2908e+00,  6.8502e-01, -5.8855e-01, -1.8873e+00],
         [ 6.9284e-01, -2.4160e+00,  1.5601e+00, -3.0469e-01],
         [ 1.0495e+00, -2.2304e+00,  1.5369e-01, -3

In [76]:
weights = torch.tensor([0.2, 0.7, 0.2])
print(weights)

tensor([0.2000, 0.7000, 0.2000])


In [10]:
six = list(range(6))
print(six)

print(six[0:-1:2])

[0, 1, 2, 3, 4, 5]
[0, 2, 4]


In [44]:
batch_t = torch.randn(2, 3, 5, 4)
print(batch_t)
print(batch_t[1, :, :, :])

tensor([[[[ 0.0385,  0.6669, -0.3904,  0.8840],
          [ 0.5292,  0.0881,  2.0464, -0.1973],
          [ 0.5935,  0.6065,  0.5704, -3.3416],
          [-1.4767,  0.0937,  0.5013, -0.7988],
          [ 0.2842, -0.8606,  0.1480,  1.1658]],

         [[-0.9276,  0.6231,  1.6399, -0.0497],
          [ 0.9660, -1.4299,  0.3242,  0.4845],
          [ 1.4609, -1.5882,  1.1152, -1.3021],
          [ 1.6852,  0.1448,  0.1294, -0.7529],
          [-1.5283,  1.3573, -1.4093,  0.2634]],

         [[-0.9983,  0.4086, -1.0001, -0.5860],
          [-0.5884,  1.9925, -0.9213,  0.1423],
          [-0.6230, -0.1902,  0.9912,  0.1667],
          [ 2.1800,  0.4442, -1.3743,  1.8211],
          [-1.4433, -1.2211,  1.3910, -0.9617]]],


        [[[-0.3758, -1.6571,  0.0703, -0.2565],
          [ 1.0019,  0.9250,  1.5358, -0.5932],
          [ 0.5428,  0.6261, -2.6765, -0.6255],
          [-0.3548, -0.0408, -0.1041, -0.2758],
          [-1.6093,  0.8337, -0.6904,  0.5156]],

         [[ 0.5191, -0.3113, -

In [50]:
print(torch.Tensor.size(torch.mean(batch_t, 0, False)))

torch.Size([3, 5, 4])


In [73]:
print(batch_t.shape)
for i in range(-4, 4):
    print(i, " ", torch.mean(batch_t, i, False).shape)
print("Min4", torch.mean(batch_t, -4, False))
print("Zero", torch.mean(batch_t, 0, False))

torch.Size([2, 3, 5, 4])
-4   torch.Size([3, 5, 4])
-3   torch.Size([2, 5, 4])
-2   torch.Size([2, 3, 4])
-1   torch.Size([2, 3, 5])
0   torch.Size([3, 5, 4])
1   torch.Size([2, 5, 4])
2   torch.Size([2, 3, 4])
3   torch.Size([2, 3, 5])
Min4 tensor([[[-0.1686, -0.4951, -0.1600,  0.3137],
         [ 0.7655,  0.5065,  1.7911, -0.3952],
         [ 0.5681,  0.6163, -1.0531, -1.9835],
         [-0.9158,  0.0265,  0.1986, -0.5373],
         [-0.6625, -0.0134, -0.2712,  0.8407]],

        [[-0.2042,  0.1559,  0.3664,  0.0409],
         [ 0.7003, -1.0607,  0.4903,  0.3082],
         [ 0.4121, -0.9417, -0.2175,  0.0388],
         [ 1.3539,  0.3058, -0.9947, -0.5632],
         [-1.9393,  0.9029, -0.8641, -0.7052]],

        [[-0.6481,  0.4211, -0.8138, -0.3555],
         [-0.6695,  1.4890, -1.1022, -0.4002],
         [ 0.6801,  0.2756,  0.3868, -0.1826],
         [ 1.7505,  0.0317, -0.3223,  1.5617],
         [-1.1743, -0.3728,  0.0271, -0.3438]]])
Zero tensor([[[-0.1686, -0.4951, -0.1600,  0.31

In [78]:
print(weights)

tensor([0.2000, 0.7000, 0.2000])


In [96]:
print(weights.unsqueeze(-1).unsqueeze_(-1).unsqueeze(0).shape)

torch.Size([1, 3, 1, 1])


In [105]:
t = torch.tensor([[1, 2], [3, 4]])
print(t.unsqueeze(0))
print(t.unsqueeze(1))
print(t.unsqueeze(2))

tensor([[[1, 2],
         [3, 4]]])
tensor([[[1, 2]],

        [[3, 4]]])
tensor([[[1],
         [2]],

        [[3],
         [4]]])


In [106]:
batch_t.refine_names('batches', 'channes', 'rows', 'columns')


C:\Users\djord\Documents\PyCharmProjects\Variance-Computation\lib\site-packages\torch\_tensor.py:1240: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at ..\c10/core/TensorImpl.h:1924.)
  return super().refine_names(names)


tensor([[[[ 0.0385,  0.6669, -0.3904,  0.8840],
          [ 0.5292,  0.0881,  2.0464, -0.1973],
          [ 0.5935,  0.6065,  0.5704, -3.3416],
          [-1.4767,  0.0937,  0.5013, -0.7988],
          [ 0.2842, -0.8606,  0.1480,  1.1658]],

         [[-0.9276,  0.6231,  1.6399, -0.0497],
          [ 0.9660, -1.4299,  0.3242,  0.4845],
          [ 1.4609, -1.5882,  1.1152, -1.3021],
          [ 1.6852,  0.1448,  0.1294, -0.7529],
          [-1.5283,  1.3573, -1.4093,  0.2634]],

         [[-0.9983,  0.4086, -1.0001, -0.5860],
          [-0.5884,  1.9925, -0.9213,  0.1423],
          [-0.6230, -0.1902,  0.9912,  0.1667],
          [ 2.1800,  0.4442, -1.3743,  1.8211],
          [-1.4433, -1.2211,  1.3910, -0.9617]]],


        [[[-0.3758, -1.6571,  0.0703, -0.2565],
          [ 1.0019,  0.9250,  1.5358, -0.5932],
          [ 0.5428,  0.6261, -2.6765, -0.6255],
          [-0.3548, -0.0408, -0.1041, -0.2758],
          [-1.6093,  0.8337, -0.6904,  0.5156]],

         [[ 0.5191, -0.3113, -